server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: packclaw

  datasource:
    url: jdbc:postgresql://localhost:5432/packclaw?currentSchema=public
    username: root
    password: lsh123456
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.packclaw


packclaw:
  dashscope:
    apiKey: sk-36498643ea35450d9d6d4d884336646e
    model: qwen3-max
